# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        ssh-port: ${{ secrets.SERVER_SSH_PORT }}
        args: "sudo chown -R www-data:www-data /var/www/html && sudo chmod -R 775 /var/www/html"
        local-ssh-port: 2222
        local-folder: ./
        server-ip: ${{ secrets.SERVER_IP }}
        server-user: ${{ secrets.SERVER_USER }}
        server-destination: /var/www/html

    - name: Start Flask API on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /var/www/html
          sudo -E nohup gunicorn -w 4 -b 0.0.0.0:5000 api:app > /dev/null 2>&1 &

    - name: Run tests
      env:
        API_URL: http://13.39.20.81:5000/predict
      run: pytest test_api.py





#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#     - name: Test with pytest
#       run: |
#         pytest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: oc-p7-creditscore
        heroku_email: samuel.planton@gmail.com
